name: Deploy Site

on:
  push:
    branches:
      - master  

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: "3.10"
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda info
          conda list
          pip install --upgrade pip setuptools
          pip install mkdocs mkdocs-material  # Ensure mkdocs is present
          python setup.py develop

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      - name: Deploy with MkDocs
        shell: bash -l {0}
        run: |
          mkdocs gh-deploy --clean --force